language: java

jdk:
  - openjdk8

services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
test:
  adapter: mysql
  database: test
  username: 'spq'@'localhost';
  encoding: utf8
dist: precise
