language: java

jdk:
  - openjdk8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
test:
 adapter: mysql
 database: test
 username: 'spq'@'localhost';
 encoding: utf8


